version: '3.8'

services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./config/local.yaml:/app/config/local.yaml
    restart: unless-stopped
